### ISSUE TITLE
Production-ready?

### ISSUE THREAD

**Issue by desmap** [benawad/express-gql#2]
Hey Ben, just saw that this lib performs quite well in your GraphQL benchmark and wonder if you use it yourself in your recipe app, so are you basically "eating your own dog food"?

**Comment by benawad** [comment]
Yep, I'm using it in Saffron right now and haven't had any problems so far.

**Comment by desmap** [comment]
Great to hear! One more question: I assume you are not using subscriptions with Saffron yet, how would subscriptions work with express-gql?

**Comment by benawad** [comment]
https://github.com/apollographql/subscriptions-transport-ws
